### ISSUE TITLE
Editor's comments

### ISSUE THREAD

**Issue by labarba** [barbagroup/bempp_exafmm_paper#13]
While we ask you to address all of the points raised, the following points need to be substantially worked on:

- [ ] Consider the missing references pointed out by Referees #2 and #3 (see below).
- [ ] Compare your software tool with other methods in the literature, as suggested by Referees #2 and #3.
- [ ] Validate your approach with problems of known solutions, as suggested by Referee #3.
- [ ] Explain your use case in more details, including why this is meaningful to the community. Provide other use cases, if possible and feasible.

Referee #2 provided the following references via email (regarding their major concerns 1 and 2):
- [ ] Major concern 1) Examples of reviews available on this topic: 

https://pubmed.ncbi.nlm.nih.gov/26874202/ -- Biochim Biophys Acta. 2016 Jul;1858(7 Pt B):1610-8. doi: 10.1016/j.bbamem.2016.02.007. Epub 2016 Feb 10. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7278654/
https://pubs.acs.org/doi/10.1021/acs.jpclett.8b02298
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6456034/

- [ ] Major concern 2) Examples of computational studies on the biology of viruses that are more relevant:

https://science.sciencemag.org/content/370/6513/203
https://www.nature.com/articles/s41586-018-0396-4

Referee #3 provided the following information/references via email (regarding their concerns 3 and 4):
- [ ] Concern 3) Grid refinement validation should be carried out for a large set of realistic biomolecules in terms of various evaluation metrics.

- [ ] Concern 4) Examples of other methods:

Li, A. and Gao, K., 2016. Accurate estimation of electrostatic binding energy with Poisson-Boltzmann equation solver DelPhi program. Journal of Theoretical and Computational Chemistry, 15(08), p.1650071.
Nguyen, D.D., Wang, B. and Wei, G.W., 2017. Accurate, robust, and reliable calculations of Poisson–Boltzmann binding energies. Journal of computational chemistry, 38(13), pp.941-948.

You will also need to make some editorial changes so that it complies with our Guide to Authors at https://www.nature.com/natcomputsci/for-authors .

In particular, I would like to highlight the following points of our style: 

- [ ] To improve the accessibility of your paper to readers from other research areas, please pay particular attention to the wording of the paper’s abstract, which serves both as an introduction and as a brief, non-technical summary in up to 150 words. It should include the background and context of the work, ‘Here we show’ or an equivalent phrase, and then the major results and conclusions of the paper. Because researchers from other sub-disciplines will be interested in your results and their implications, it is important to explain essential but specialized terms concisely. We suggest you show your summary paragraph to colleagues in other fields to uncover any problematic concepts. We discourage having references, links, and detailed code/hardware information in the abstract, as this information will come in the Code Availability statement.

**Comment by labarba** [comment]
commit at time of submission: ee28810cf09bfd9ba49d9da3f9b05ee18160f10c

We can use [`git-latexdiff`](http://www.deanbodenham.com/learn/git-and-latexdiff.html) to highlight the changes between submitted and revised versions, as requested by the editor.

**Comment by labarba** [comment]
Abstract: we went from 342 words in bd34595 to 215 in 1c9c671

**Comment by labarba** [comment]
# Cover letter to the editor
​
While we ask you to address all of the points raised, the following points need to be substantially worked on:
​
1. Consider the missing references pointed out by Referees #2 and #3 (see below).
​
We have cited the literature on coarse grained models suggested by Referee #2 in the introduction section.
​
Referee #3 suggested two references as examples to show that grid refinement study should be carried out for a large set of realistic biomolecules: Li and Gao's paper studies the effect of grid spacing on binding free energy in DelPhi; Nguyen etal's paper investigates the grid convergence of the binding free energy using MIBPB. We cited both software (DelPhi and MIBPB) in our revision. We improved the grid convergence study by using 8 more proteins and compared our results with those from APBS and MIBPB.
​
2. Compare your software tool with other methods in the literature, as suggested by Referees #2 and #3.
​
This revision introduces new grid-convergence study with 9 different molecules, and result comparison with APBS (in the result section) and MIBPB (in the appendix).
​
3. Validate your approach with problems of known solutions, as suggested by Referee #3.
​
We have already verified our software with an analytical solution using Kirkwood's sphere. Such analytical solution is not available for real molecules. Our new results show agreements with APBS and MIBPB using 9 real molecules.

**Comment by labarba** [comment]
4. Explain your use case in more details, including why this is meaningful to the community. Provide other use cases, if possible and feasible.

**Comment by labarba** [comment]
**Cover letter to the editor**, 
[Cover_letter_to_the_editor.pdf](https://github.com/barbagroup/bempp_exafmm_paper/files/7274774/Cover_letter_to_the_editor.pdf)
